-- ═══════════════════════════════════════════════════════
-- BhojanSeva Full Schema v2
-- Run this in Supabase SQL Editor → New Query → Run All
-- ═══════════════════════════════════════════════════════

-- Enable PostGIS extension (for spatial queries)
CREATE EXTENSION IF NOT EXISTS postgis;

-- ───────────────────────────────────────────────────────
-- TABLE: sevas (main listings)
-- ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.sevas (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  title         text NOT NULL,
  food          text NOT NULL,
  type          text NOT NULL,
  permanence    text DEFAULT 'temporary',
  is_live       boolean DEFAULT true,
  status        text DEFAULT 'serving',
  is_sos        boolean DEFAULT false,
  tags          text[] DEFAULT '{}'::text[],
  allergens     text[] DEFAULT '{}'::text[],
  finished_votes bigint[] DEFAULT '{}'::bigint[],
  location      jsonb NOT NULL,
  geo_point     geography(Point, 4326),   -- PostGIS spatial column
  distance      text,
  time          text,
  start_time    timestamptz,
  end_time      timestamptz,
  estimated_servings integer DEFAULT 0,
  servings_left  integer DEFAULT 0,
  going_count   integer DEFAULT 0,
  trust_score   integer DEFAULT 100,
  is_moving     boolean DEFAULT false,
  is_verified   boolean DEFAULT false,
  is_featured   boolean DEFAULT false,
  photo_url     text,
  photo_urls    text[] DEFAULT '{}'::text[],
  sponsor_name  text,
  sponsor_amount integer DEFAULT 0,
  city          text DEFAULT 'Delhi',
  contribution_score integer DEFAULT 0,
  report_count  integer DEFAULT 0,
  ai_description text,
  created_at    timestamptz DEFAULT timezone('utc', now()) NOT NULL,
  updated_at    timestamptz DEFAULT timezone('utc', now())
);

-- Spatial index for fast proximity queries
CREATE INDEX IF NOT EXISTS idx_sevas_geo ON public.sevas USING GIST (geo_point);
CREATE INDEX IF NOT EXISTS idx_sevas_city ON public.sevas (city);
CREATE INDEX IF NOT EXISTS idx_sevas_is_live ON public.sevas (is_live);
CREATE INDEX IF NOT EXISTS idx_sevas_user_id ON public.sevas (user_id);

-- Auto-update updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_sevas_updated_at ON public.sevas;
CREATE TRIGGER update_sevas_updated_at
  BEFORE UPDATE ON public.sevas
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ───────────────────────────────────────────────────────
-- TABLE: seva_votes (crowd status votes)
-- ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.seva_votes (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seva_id    bigint REFERENCES public.sevas(id) ON DELETE CASCADE,
  voter_fingerprint text,   -- browser fingerprint (no login required)
  vote_type  text NOT NULL CHECK (vote_type IN ('serving','low','finished','trust_up','trust_down')),
  created_at timestamptz DEFAULT timezone('utc', now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_votes_seva_id ON public.seva_votes (seva_id);
CREATE INDEX IF NOT EXISTS idx_votes_created ON public.seva_votes (created_at);

-- ───────────────────────────────────────────────────────
-- TABLE: going_tracking (I'm Going)
-- ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.going_tracking (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seva_id    bigint REFERENCES public.sevas(id) ON DELETE CASCADE,
  user_fingerprint text NOT NULL,
  created_at timestamptz DEFAULT timezone('utc', now()) NOT NULL,
  UNIQUE(seva_id, user_fingerprint)
);

-- ───────────────────────────────────────────────────────
-- TABLE: saved_sevas (bookmarks)
-- ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.saved_sevas (
  id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  seva_id bigint REFERENCES public.sevas(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT timezone('utc', now()) NOT NULL,
  UNIQUE(user_id, seva_id)
);

-- ───────────────────────────────────────────────────────
-- TABLE: audit_log (moderation trail)
-- ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.audit_log (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seva_id    bigint REFERENCES public.sevas(id) ON DELETE CASCADE,
  user_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action     text NOT NULL,
  old_value  jsonb,
  new_value  jsonb,
  created_at timestamptz DEFAULT timezone('utc', now()) NOT NULL
);

-- ───────────────────────────────────────────────────────
-- TABLE: reports (anonymous flagging)
-- ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.reports (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seva_id    bigint REFERENCES public.sevas(id) ON DELETE CASCADE,
  reason     text NOT NULL,
  details    text,
  reporter_fingerprint text,
  created_at timestamptz DEFAULT timezone('utc', now()) NOT NULL
);

-- ───────────────────────────────────────────────────────
-- TABLE: user_profiles (contribution scores)
-- ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id               uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name     text,
  avatar_url       text,
  city             text DEFAULT 'Delhi',
  contribution_score integer DEFAULT 0,
  sevas_added      integer DEFAULT 0,
  sevas_verified   integer DEFAULT 0,
  is_verified_organizer boolean DEFAULT false,
  is_ngo           boolean DEFAULT false,
  bio              text,
  created_at       timestamptz DEFAULT timezone('utc', now()) NOT NULL
);

-- ───────────────────────────────────────────────────────
-- ROW LEVEL SECURITY
-- ───────────────────────────────────────────────────────
ALTER TABLE public.sevas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seva_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.going_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_sevas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

-- Drop old policies first
DROP POLICY IF EXISTS "Allow public read access" ON public.sevas;
DROP POLICY IF EXISTS "Allow public insert access" ON public.sevas;
DROP POLICY IF EXISTS "Allow public update access" ON public.sevas;

-- Sevas: public read, authenticated insert, owner update/delete
CREATE POLICY "sevas_read" ON public.sevas FOR SELECT USING (true);
CREATE POLICY "sevas_insert" ON public.sevas FOR INSERT WITH CHECK (true);
CREATE POLICY "sevas_update_own" ON public.sevas FOR UPDATE USING (user_id = auth.uid() OR user_id IS NULL);
CREATE POLICY "sevas_delete_own" ON public.sevas FOR DELETE USING (user_id = auth.uid());

-- Votes: public read/insert
CREATE POLICY "votes_read" ON public.seva_votes FOR SELECT USING (true);
CREATE POLICY "votes_insert" ON public.seva_votes FOR INSERT WITH CHECK (true);

-- Going: public read/insert
CREATE POLICY "going_read" ON public.going_tracking FOR SELECT USING (true);
CREATE POLICY "going_insert" ON public.going_tracking FOR INSERT WITH CHECK (true);
CREATE POLICY "going_delete" ON public.going_tracking FOR DELETE USING (true);

-- Saved sevas: own user only
CREATE POLICY "saved_read" ON public.saved_sevas FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "saved_insert" ON public.saved_sevas FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "saved_delete" ON public.saved_sevas FOR DELETE USING (user_id = auth.uid());

-- Reports: public insert
CREATE POLICY "reports_insert" ON public.reports FOR INSERT WITH CHECK (true);

-- User profiles: public read, own update
CREATE POLICY "profiles_read" ON public.user_profiles FOR SELECT USING (true);
CREATE POLICY "profiles_insert" ON public.user_profiles FOR INSERT WITH CHECK (id = auth.uid());
CREATE POLICY "profiles_update" ON public.user_profiles FOR UPDATE USING (id = auth.uid());

-- Audit log: public read
CREATE POLICY "audit_read" ON public.audit_log FOR SELECT USING (true);

-- ───────────────────────────────────────────────────────
-- FUNCTION: get_sevas_near (PostGIS proximity search)
-- ───────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION get_sevas_near(
  lat float8, lng float8, radius_km float8 DEFAULT 10
)
RETURNS SETOF public.sevas AS $$
  SELECT * FROM public.sevas
  WHERE is_live = true
    AND ST_DWithin(
      geo_point,
      ST_MakePoint(lng, lat)::geography,
      radius_km * 1000
    )
  ORDER BY geo_point <-> ST_MakePoint(lng, lat)::geography;
$$ LANGUAGE sql STABLE;

-- ───────────────────────────────────────────────────────
-- REALTIME: Enable for key tables
-- ───────────────────────────────────────────────────────
ALTER PUBLICATION supabase_realtime ADD TABLE public.sevas;
ALTER PUBLICATION supabase_realtime ADD TABLE public.seva_votes;
ALTER PUBLICATION supabase_realtime ADD TABLE public.going_tracking;

-- ───────────────────────────────────────────────────────
-- STORAGE: Create seva-photos bucket
-- ───────────────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'seva-photos', 'seva-photos', true,
  5242880,  -- 5MB
  ARRAY['image/jpeg','image/png','image/webp','image/gif']
) ON CONFLICT (id) DO NOTHING;

-- Storage access policies
DROP POLICY IF EXISTS "seva_photos_read" ON storage.objects;
DROP POLICY IF EXISTS "seva_photos_insert" ON storage.objects;
CREATE POLICY "seva_photos_read" ON storage.objects FOR SELECT USING (bucket_id = 'seva-photos');
CREATE POLICY "seva_photos_insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'seva-photos');

-- ───────────────────────────────────────────────────────
-- SEED DATA (v2 with all new fields)
-- ───────────────────────────────────────────────────────
INSERT INTO public.sevas (
  title, food, type, permanence, is_live, status, is_sos, tags, allergens,
  location, distance, time, estimated_servings, servings_left, going_count,
  trust_score, is_moving, is_verified, city, ai_description
) VALUES
(
  'Gurudwara Bangla Sahib Langar', 'Dal Makhani, Roti, Rice, Kheer',
  'Langar', 'permanent', true, 'serving', false,
  ARRAY['Full Meal','Jain'], ARRAY['Dairy'],
  '{"lat":28.6264,"lng":77.2091}', '1.2 km away',
  'Daily: 11:00 AM - 9:00 PM', 2000, 1800, 47,
  98, false, true, 'Delhi',
  'A divine community kitchen offering unlimited wholesome meals prepared with love and devotion, serving thousands every day.'
),
(
  'Sunday CP Hanuman Mandir Bhandara', 'Puri Chole & Sooji Halwa',
  'Bhandara', 'temporary', true, 'serving', false,
  ARRAY['Full Meal'], ARRAY[],
  '{"lat":28.6139,"lng":77.2090}', '0.8 km away',
  'Sundays: 12:00 PM - 3:00 PM', 500, 350, 23,
  92, false, true, 'Delhi',
  'Golden fried Puris with spiced Chole and freshly made Sooji Halwa — a beloved Sunday tradition at the heart of Delhi.'
),
(
  'Mobile Food Van — CP Outer Circle', 'Food Packets (Rajma Rice)',
  'Bhandara', 'temporary', true, 'serving', true,
  ARRAY['Full Meal','Snacks'], ARRAY['Gluten'],
  '{"lat":28.6310,"lng":77.2180}', '0.4 km away',
  'Active now', 200, 80, 12,
  88, true, false, 'Delhi',
  'Freshly packed Rajma Chawal meals distributed from a moving van — track the live pin to intercept it near you!'
),
(
  'Summer Chabeel Water Stand', 'Sweet Rose Sherbet & Cold Water',
  'Other', 'temporary', true, 'serving', false,
  ARRAY['Drinking Water'], ARRAY[],
  '{"lat":28.6230,"lng":77.2150}', '0.5 km away',
  '10:00 AM - 5:00 PM', 1000, 700, 8,
  95, false, false, 'Delhi',
  'Cool rose-flavored sherbet and chilled water — a refreshing summer Seva combating the scorching Delhi heat.'
)
ON CONFLICT DO NOTHING;
